const data = {
  products: [
    {
        "_id" : "1",
        "name" : "Baklawa",
        "category" : "Gâteau au miel",
        "image" : "/images/p1.jpg",
        "price" : 120,
        "countInStock" : 10,
        "brand" : 23,
        "rating" : 4.5,
        "numReviews" : 10,
        "description" : "high quality product",
        "reviews" : [],
    },
    {
        "_id" : "2",
        "name" : "Makroudh",
        "category" : "Gâteau au miel",
        "image" : "/images/p2.png",
        "price" : 100,
        "countInStock" : 20,
        "brand" : 5,
        "rating" : 4,
        "numReviews" : 10,
        "description" : "Makroudh tunisien",
        "reviews" : [],
    },
    {
        "_id" : "3",
        "name" : "Grawich",
        "category" : "Gâteau au miel",
        "image" : "/images/p3.jpg",
        "price" : 220,
        "countInStock" : 0,
        "brand" : 12,
        "rating" : 4.8,
        "numReviews" : 17,
        "description" : "high quality grawich yitgharmich",
        "reviews" : [],
    },
    {
        "_id" : "4",
        "name" : "Sablés fondants à la confiture",
        "category" : "Gâteau sec",
        "image" : "/images/p4.jpg",
        "price" : 78,
        "countInStock" : 15,
        "brand" : 14,
        "rating" : 5,
        "numReviews" : 1,
        "description" : "Que diriez-vous de sablés pour le gouter ?? mais ceux-la sont ultra fondants à la confiture. J’ai déjà une série de recettes de biscuits sur mon blog pour des évènements spéciaux ou tout simplement un après-midi en famille ou entre amis autour d’un café ou un thé à la menthe.Une recette qui reste très facile, l’ajout de la maïzena les rend fondants à souhait. Ma petite touche je badigeonne le sable de blanc d’oeuf et je saupoudre de pistaches concassées que vous pouvez remplacer par des amandes ou noisettes concassées ou tout simplement les saupoudrer de sucre glace.Cette recette je l’ai déniché chez ma chère Ranouza du joli blog Un brin de gourmandise.Cette année j’ai décidé de participer à des jeux culinaires cela permet de sortir un peu de la routine mais aussi de découvrir de nouveaux blogs et de tester des recettes ! Et le 23 du mois c’est au tour de Foodista Challenge, c’est ma première participation 🙂",
        "reviews" : [ 
            {
                "_id" : ObjectId("5fd5cc09ee87ee8b7c73b06f"),
                "name" : "Malika Tahri",
                "rating" : 5,
                "comment" : "Vraiment le Sablés fondants à la confiture sont délicieux",
                "createdAt" : ISODate("2020-12-13T08:08:41.639Z"),
                "updatedAt" : ISODate("2020-12-13T08:08:41.639Z")
            }
        ],
    },
    {
        "_id" : "5",
        "name" : "Les manicotti tunisiens (Deblah)",
        "category" : "Gâteau au miel",
        "image" : "/images/p5.jpg",
        "price" : 65,
        "countInStock" : 5,
        "brand" : 18,
        "rating" : 4.5,
        "numReviews" : 10,
        "description" : "Une recette de famille aujourd'hui, avec un incontournable de la cuisine juive tunisienne, les manicotti",
        "reviews" : [],
    },
    {
      _id: '6',
      "name" : "sablés au nutella",
      "seller" : ObjectId("5fd54281ee87ee8b7c73b06c"),
      "category" : "Gâteau sec",
      "image" : "/images/p6.jpg",
      "price" : 139,
      "countInStock" : 12,
      "brand" : 33,
      "rating" : 4.5,
      "numReviews" : 15,
      "description" : " ils sont très fondants a la bouche, facile a réaliser et avec des ingrédients simples.",
      "reviews" : [],
    },
  ],
};
export default data;
